db_name: servicebroker
db_port: "3306"
gcp_service_broker_enable_global_access_to_plans: true
gsb_brokerpak_config: '{}'
gsb_compatibility_enable_builtin_brokerpaks: "true"
gsb_compatibility_enable_builtin_services: "true"
gsb_compatibility_enable_catalog_schemas: "false"
gsb_compatibility_enable_cf_sharing: "false"
gsb_compatibility_enable_eol_services: "false"
gsb_compatibility_enable_gcp_beta_services: "true"
gsb_compatibility_enable_gcp_deprecated_services: "false"
gsb_compatibility_enable_preview_services: "true"
gsb_compatibility_enable_terraform_services: "false"
gsb_compatibility_enable_unmaintained_services: "false"
gsb_service_google_bigquery_bind_defaults: '{}'
gsb_service_google_bigquery_provision_defaults: '{}'
gsb_service_google_bigtable_bind_defaults: '{}'
gsb_service_google_bigtable_provision_defaults: '{}'
gsb_service_google_cloudsql_mysql_bind_defaults: '{}'
gsb_service_google_cloudsql_mysql_provision_defaults: '{}'
gsb_service_google_cloudsql_mysql_vpc_bind_defaults: '{}'
gsb_service_google_cloudsql_mysql_vpc_provision_defaults: '{}'
gsb_service_google_cloudsql_postgres_bind_defaults: '{}'
gsb_service_google_cloudsql_postgres_provision_defaults: '{}'
gsb_service_google_cloudsql_postgres_vpc_bind_defaults: '{}'
gsb_service_google_cloudsql_postgres_vpc_provision_defaults: '{}'
gsb_service_google_ml_apis_bind_defaults: '{}'
gsb_service_google_ml_apis_provision_defaults: '{}'
gsb_service_google_pubsub_bind_defaults: '{}'
gsb_service_google_pubsub_provision_defaults: '{}'
gsb_service_google_spanner_bind_defaults: '{}'
gsb_service_google_spanner_provision_defaults: '{}'
gsb_service_google_storage_bind_defaults: '{}'
gsb_service_google_storage_provision_defaults: '{}'
