---
platform: linux
image_resource:
  type: docker-image
  source: {repository: m0pt0pmatt/omgci}
inputs:
- name: omg-src-in
- name: omg-env
  path: omg-env-in
outputs:
- name: omg-env
  path: omg-env-out
run:
  path: omg-src-in/ci/tasks/destroy-infrastructure.sh
