---
platform: linux
image_resource:
  type: docker-image
  source: {repository: m0pt0pmatt/omgci}
inputs:
- name: omg-src-in
run:
  path: omg-src-in/ci/tasks/prepare-project.sh
params:
  google_project: replace-me
  google_json_key_data: replace-me
  env_config: replace-me
