---
platform: linux
image_resource:
  type: docker-image
  source: {repository: m0pt0pmatt/omgci}
inputs:
  - name: omg-src-in
  - name: release-version-semver
outputs:
  - name: promoted
run:
  path: omg-src-in/ci/tasks/promote-candidate.sh
