---
platform: linux
image_resource:
  type: docker-image
  source: {repository: jrjohnsongoog/omgci}
inputs:
- name: omg-src-in
  path: omg-src-develop
- name: omg-src-master
- name: omg-src-ci
- name: omg-env
  path: omg-env-in
- name: version
outputs:
- name: release
- name: omg-src-develop
run:
  path: omg-src-ci/ci/tasks/finalize-release.sh
