---
platform: linux
image_resource:
  type: docker-image
  source: {repository: jrjohnsongoog/omgci}
inputs:
- name: omg-src-develop
- name: omg-src-ci
- name: version
outputs:
- name: release
- name: omg-src-develop
run:
  path: omg-src-ci/ci/tasks/shipit.sh
